(async function(){
  const $=s=>document.querySelector(s),sb=getSupabase();if(window.lucide)lucide.createIcons();
  const gate=$("#readerGate"),app=$("#readerApp"),errorBox=$("#readerError"),title=$("#readerTitle"),pageImg=$("#pageImage"),loading=$("#pageLoading"),pageCountEl=$("#pageCount"),pageInput=$("#pageInput"),prev=$("#prevBtn"),next=$("#nextBtn"),progressLabel=$("#progressLabel"),progressText=$("#progressText"),watermark=$("#watermark");
  const params=new URLSearchParams(location.search),bookId=params.get('book');let pages=[],current=1,book=null,user=null,loadingPage=false;
  function icons(){if(window.lucide)lucide.createIcons()}
  function showError(text){gate.hidden=true;app.hidden=true;errorBox.hidden=false;errorBox.innerHTML=`<i data-lucide="circle-alert"></i><h2>Unable to open this book</h2><p>${String(text).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}</p><a href="library.html" class="reader-back-link">Return to My Library</a>`;icons()}
  async function getUser(){const {data,error}=await sb.auth.getUser();if(error)throw error;return data.user}
  async function saveProgress(){if(!user||!book||!pages.length)return;const pct=Math.round((current/pages.length)*100);const {error}=await sb.from('reading_progress').upsert({user_id:user.id,book_id:book.id,current_page:current,progress_percent:pct,last_read_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'user_id,book_id'});if(!error){progressText.textContent=`${Math.round(pct)}% complete`;progressLabel.textContent=`${Math.round(pct)}%`}}
  async function loadPage(n){if(loadingPage||!pages.includes(n))return;loadingPage=true;current=n;pageInput.value=n;prev.disabled=n<=pages[0];next.disabled=n>=pages[pages.length-1];loading.hidden=false;pageImg.hidden=true;try{const {data,error}=await sb.functions.invoke('reader-page',{body:{bookId,page:n}});if(error)throw error;if(data?.error)throw new Error(data.error);pageImg.onload=()=>{loading.hidden=true;pageImg.hidden=false;loadingPage=false};pageImg.onerror=()=>{loadingPage=false;showError('The secure page image could not be loaded.')};pageImg.src=data.url;await saveProgress()}catch(e){loadingPage=false;showError(/auth|session|access|entitlement|not authenticated/i.test(String(e?.message||''))?'Your reading access is no longer available. Please return to My Library.':'Unable to load this secure page.')}}
  try{if(!sb)throw new Error('Supabase is not configured.');if(!bookId)throw new Error('No book was selected.');user=await getUser();if(!user){location.href=`library.html?return=${encodeURIComponent(location.href)}`;return}const {data,error}=await sb.functions.invoke('reader-manifest',{body:{bookId}});if(error)throw error;if(data?.error)throw new Error(data.error);book=data.book;pages=data.pages||[];if(!pages.length)throw new Error('This book has no reader pages yet.');title.textContent=book.title;pageCountEl.textContent=pages.length;watermark.textContent=`${user.email} · DENNIS NAZAR DIGITAL EDITION`;const {data:p}=await sb.from('reading_progress').select('current_page,progress_percent').eq('user_id',user.id).eq('book_id',book.id).maybeSingle();current=pages.includes(Number(p?.current_page))?Number(p.current_page):pages[0];gate.hidden=true;app.hidden=false;icons();await loadPage(current)}catch(e){showError(/auth|session|access|entitlement|not authenticated/i.test(String(e?.message||''))?'Your secure reading session or entitlement is not valid.':'Unable to open this private book.')}
  prev?.addEventListener('click',()=>{const i=pages.indexOf(current);if(i>0)loadPage(pages[i-1])});next?.addEventListener('click',()=>{const i=pages.indexOf(current);if(i>=0&&i<pages.length-1)loadPage(pages[i+1])});pageInput?.addEventListener('change',()=>{const n=Number(pageInput.value);if(pages.includes(n))loadPage(n);else pageInput.value=current});document.addEventListener('keydown',e=>{if(app.hidden)return;if(e.key==='ArrowLeft')prev.click();if(e.key==='ArrowRight')next.click()});pageImg?.addEventListener('contextmenu',e=>e.preventDefault());sb?.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT')showError('Your secure reading session has ended. Please sign in again.')});
})();
