(async function(){
  const $=s=>document.querySelector(s),sb=getSupabase();if(window.lucide)lucide.createIcons();
  const gate=$("#readerGate"),app=$("#readerApp"),errorBox=$("#readerError"),title=$("#readerTitle"),pageImg=$("#pageImage"),loading=$("#pageLoading"),pageCountEl=$("#pageCount"),pageInput=$("#pageInput"),prev=$("#prevBtn"),next=$("#nextBtn"),progressLabel=$("#progressLabel"),progressText=$("#progressText"),watermark=$("#watermark");
  const params=new URLSearchParams(location.search),bookId=params.get('book');let pages=[],current=1,book=null,user=null,loadingPage=false;
  function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function icons(){if(window.lucide)lucide.createIcons()}
  function showError(text){gate.hidden=true;app.hidden=true;errorBox.hidden=false;errorBox.innerHTML=`<i data-lucide="circle-alert"></i><h2>Unable to open this book</h2><p>${String(text).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}</p><a href="library.html" class="reader-back-link">Return to My Library</a>`;icons()}
  async function getUser(){const {data,error}=await sb.auth.getUser();if(error)throw error;return data.user}
  async function saveProgress(){if(!user||!book||!pages.length)return;const pct=Math.round((current/pages.length)*100);const {error}=await sb.from('reading_progress').upsert({user_id:user.id,book_id:book.id,current_page:current,progress_percent:pct,last_read_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'user_id,book_id'});if(!error){progressText.textContent=`${Math.round(pct)}% complete`;progressLabel.textContent=`${Math.round(pct)}%`}}
  async function loadPage(n){if(loadingPage||!pages.includes(n))return;loadingPage=true;current=n;pageInput.value=n;prev.disabled=n<=pages[0];next.disabled=n>=pages[pages.length-1];loading.hidden=false;pageImg.hidden=true;try{const {data,error}=await sb.functions.invoke('reader-page',{body:{bookId,page:n}});if(error)throw error;if(data?.error)throw new Error(data.error);pageImg.onload=()=>{loading.hidden=true;pageImg.hidden=false;loadingPage=false};pageImg.onerror=()=>{loadingPage=false;showError('The secure page image could not be loaded.')};pageImg.src=data.url;await saveProgress()}catch(e){loadingPage=false;showError(/auth|session|access|entitlement|not authenticated/i.test(String(e?.message||''))?'Your reading access is no longer available. Please return to My Library.':'Unable to load this secure page.')}}
  try{if(!sb)throw new Error('Supabase is not configured.');if(!bookId)throw new Error('No book was selected.');user=await getUser();if(!user){location.href=`library.html?return=${encodeURIComponent(location.href)}`;return}const {data,error}=await sb.functions.invoke('reader-manifest',{body:{bookId}});if(error)throw error;if(data?.error)throw new Error(data.error);book=data.book;pages=data.pages||[];if(!pages.length)throw new Error('This book has no reader pages yet.');title.textContent=book.title;pageCountEl.textContent=pages.length;const purchase=data.purchase||{};const customerName=purchase.customerName||user.user_metadata?.full_name||user.user_metadata?.name||'';const customerEmail=purchase.customerEmail||user.email||'';const orderNumber=purchase.orderNumber||'UNVERIFIED';const wmName=escapeHtml(customerName||customerEmail),wmEmail=escapeHtml(customerEmail),wmOrder=escapeHtml(orderNumber);watermark.innerHTML=Array.from({length:6},()=>`<div class="watermark-stamp"><span>LICENSED TO ${wmName}</span><span>ORDER ${wmOrder}</span><span>${wmEmail} · UNAUTHORIZED SHARING PROHIBITED</span></div>`).join('');const {data:p}=await sb.from('reading_progress').select('current_page,progress_percent').eq('user_id',user.id).eq('book_id',book.id).maybeSingle();current=pages.includes(Number(p?.current_page))?Number(p.current_page):pages[0];gate.hidden=true;app.hidden=false;icons();await loadPage(current)}catch(e){showError(/auth|session|access|entitlement|not authenticated/i.test(String(e?.message||''))?'Your secure reading session or entitlement is not valid.':'Unable to open this private book.')}
  prev?.addEventListener('click',()=>{const i=pages.indexOf(current);if(i>0)loadPage(pages[i-1])});next?.addEventListener('click',()=>{const i=pages.indexOf(current);if(i>=0&&i<pages.length-1)loadPage(pages[i+1])});pageInput?.addEventListener('change',()=>{const n=Number(pageInput.value);if(pages.includes(n))loadPage(n);else pageInput.value=current});document.addEventListener('keydown',e=>{if(app.hidden)return;if(e.key==='ArrowLeft')prev.click();if(e.key==='ArrowRight')next.click()});const swipeTarget=$("#readerStage")||$(".reader-stage");let touchStartX=0,touchStartY=0,touchStartTime=0,touchActive=false;
  swipeTarget?.addEventListener('touchstart',e=>{if(e.touches.length!==1||loadingPage)return;const t=e.touches[0];touchStartX=t.clientX;touchStartY=t.clientY;touchStartTime=Date.now();touchActive=true},{passive:true});
  swipeTarget?.addEventListener('touchmove',e=>{if(!touchActive||e.touches.length!==1)return;const t=e.touches[0],dx=t.clientX-touchStartX,dy=t.clientY-touchStartY;if(Math.abs(dx)>12&&Math.abs(dx)>Math.abs(dy)*1.15)e.preventDefault()},{passive:false});
  swipeTarget?.addEventListener('touchend',e=>{if(!touchActive)return;touchActive=false;const t=e.changedTouches[0],dx=t.clientX-touchStartX,dy=t.clientY-touchStartY,dt=Date.now()-touchStartTime;const distance=Math.abs(dx),vertical=Math.abs(dy);if(dt<=650&&distance>=55&&distance>vertical*1.2){if(dx<0)next.click();else prev.click()}},{passive:true});
  pageImg?.addEventListener('contextmenu',e=>e.preventDefault());sb?.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT')showError('Your secure reading session has ended. Please sign in again.')});
})();
