/* Dennis Nazar Store — shared frontend + Supabase bridge */
const DEFAULT_STORE = {
  author:"Dennis Nazar", currency:"TZS", email:"dennisnazar123@gmail.com", paymentPhone:"+255765889395", whatsapp:"+255765889395", mapLocation:"66MH+QCF Dar es Salaam, Tanzania", socialUsername:"@dennisnazar_",
  colors:{navy:"#211d5a",navy2:"#181443",orange:"#f47721",orange2:"#ff8a2d"},
  content:{
    heroTitle:"Books that <span>shape</span><br>how you <span>think.</span>",heroLead:"Vitabu vinavyogusa maisha, mahusiano, kusudi, maamuzi na ukuaji binafsi — vikiwa vimeandikwa kwa mtazamo wa maisha halisi.<br>Kila ukurasa unakupa nafasi ya kutafakari, kujifunza na kuchukua hatua mpya.<br>Chagua kitabu kinachokuhusu na uruhusu ujumbe wake ubadili mtazamo wako wa maisha.",booksCopy:"Chagua kitabu, kamilisha malipo na upokee softcopy yako kwa hatua rahisi.",whyTitle:"More than a <span>book.</span>",whyLead:"Maandishi yanayokusukuma kufikiri, kutafakari na kuchukua hatua.",comingTitle:"More Books Are <span>Coming.</span>",comingCopy:"Vitabu viwili vipya bado vinaandaliwa. Fuata updates ili uwe wa kwanza kujua vinapotoka.",aboutTitle:"Dennis <span>Nazar.</span>",aboutBody:"Dennis Nazar ni mwandishi wa vitabu, mwalimu wa Biblia, mkufunzi mwelekezi (mentor) na mshauri katika masuala ya uongozi, afya, ndoa na familia.\n\nAmetoa mchango mkubwa katika kujenga kizazi cha vijana wanaoelewa kusudi lao, ukuaji binafsi na nguvu ya kutembea katika maono ya Mungu kupitia programu ya ELEVATED LIFE SERIES.\n\nAkiwa na stashahada ya juu ya ufamasia kutoka NOCOHAS pamoja na shahada ya Theology kutoka AUCA, Kigali-Rwanda, ameunganisha maarifa ya afya ya mwili, afya ya akili na mafundisho ya kiroho.\n\nAnaamini kila kijana amewekewa ndani yake maono, ndoto na wito unaokusudiwa kuibua thamani yake duniani — na kupitia maandishi na mafundisho yake, anahamasisha watu kuishi maisha ya kusudi, kanuni na uongozi wenye maadili.",purchaseTitle:"Get notified about<br><span>your next book.</span>",purchaseCopy:"Weka email yako ili upokee taarifa kuhusu releases mpya, order updates na Library access.",footerTagline:"Books that inspire thought, reflection & better living."
  }
};
const DEFAULT_BOOKS={
  book1:{title:"HATUA 10 ZA KUCHAGUA MWENZI SAHIHI WA MAISHA",subtitle:"Mwongozo wa kujitambua na kufanya maamuzi ya busara unapochagua mwenzi wa maisha, ukiangalia tabia, mawasiliano, maadili na mwelekeo wa baadaye.",price:2500,image:"assets/book-1.webp",available:true,pdfUrl:"",sort_order:1},
  book2:{title:"MAAJABU YA MWANAMKE",subtitle:"Kitabu kinachomsaidia mwanamke kutafakari thamani yake, nafasi yake na nguvu alizonazo, huku kikigusa kujiamini, mahusiano na safari ya ukuaji binafsi.",price:2500,image:"assets/book-2.webp",available:true,pdfUrl:"",sort_order:2},
  book3:{title:"HISTORIA YAKO ITASOMEKAJE?",subtitle:"Mwongozo wa kutafakari alama unazoacha katika maisha ya wengine, maamuzi unayofanya leo na namna ya kujenga historia yenye maana, kusudi na matokeo mema.",price:2500,image:"assets/book-3.webp",available:true,pdfUrl:"",sort_order:3},
  book4:{title:"Kitabu kipya kinakuja",subtitle:"NEW RELEASE",price:0,image:"assets/coming-soon-cover.jpg",available:false,pdfUrl:"",sort_order:4},
  book5:{title:"Hadithi nyingine inakuja",subtitle:"NEW RELEASE",price:0,image:"assets/coming-soon-cover-04.jpg",available:false,pdfUrl:"",sort_order:5}
};
function normalizeAssetPath(path){const v=String(path||"").trim();if(v==="assets/book-3.jpg"||v==="assets/book-3.jpeg")return "assets/book-3.webp";if(v==="assets/coming-soon-cover.jpg"||v==="assets/coming-soon-cover.jpeg")return "assets/coming-soon-cover.webp";if(v==="assets/coming-soon-cover-04.jpg"||v==="assets/coming-soon-cover-04.jpeg")return "assets/coming-soon-cover-04.webp";return v}
function deepMerge(a,b){const o={...a};for(const k of Object.keys(b||{})){if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k])&&a[k])o[k]=deepMerge(a[k],b[k]);else o[k]=b[k]}return o}
function getStoreConfig(){try{return deepMerge(DEFAULT_STORE,JSON.parse(localStorage.getItem('dennisNazarStoreConfig'))||{})}catch{return deepMerge(DEFAULT_STORE,{})}}
function getBooks(){try{return deepMerge(DEFAULT_BOOKS,JSON.parse(localStorage.getItem('dennisNazarBooks'))||{})}catch{return deepMerge(DEFAULT_BOOKS,{})}}
function saveStoreConfig(c){localStorage.setItem('dennisNazarStoreConfig',JSON.stringify(c))}
function saveBooks(b){localStorage.setItem('dennisNazarBooks',JSON.stringify(b))}
function getCart(){try{return JSON.parse(localStorage.getItem('dennisNazarCart'))||[]}catch{return[]}}
function saveCart(c){localStorage.setItem('dennisNazarCart',JSON.stringify(c))}
function clearCart(){localStorage.removeItem('dennisNazarCart')}
function formatPrice(v){const s=getStoreConfig();return `${Number(v).toLocaleString('en-US')} ${s.currency}`}
function createOrderId(){const d=new Date(),date=`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`;return `DN-${date}-${Math.random().toString(36).slice(2,8).toUpperCase()}`}
function hasSupabase(){return !!(window.supabase && window.DN_SUPABASE_CONFIG && window.DN_SUPABASE_CONFIG.url && !window.DN_SUPABASE_CONFIG.url.includes('YOUR-PROJECT') && window.DN_SUPABASE_CONFIG.publishableKey && !window.DN_SUPABASE_CONFIG.publishableKey.includes('YOUR_'))}
function getSupabase(){if(!hasSupabase())return null;if(!window.__dnSupabase)window.__dnSupabase=window.supabase.createClient(window.DN_SUPABASE_CONFIG.url,window.DN_SUPABASE_CONFIG.publishableKey);return window.__dnSupabase}
async function loadBackendStore(){const sb=getSupabase();if(!sb)return {config:getStoreConfig(),books:getBooks(),backend:false};try{const [{data:settings,error:sErr},{data:rows,error:bErr}]=await Promise.all([sb.from('store_settings').select('data').eq('id',1).maybeSingle(),sb.from('books').select('id,title,subtitle,price,image_path,available,sort_order,updated_at,slug,description,author,currency,status,created_at').order('sort_order')]);if(sErr||bErr)throw(sErr||bErr);const config=deepMerge(DEFAULT_STORE,settings?.data||{});const books=Object.fromEntries((rows||[]).map(b=>[b.id,{title:b.title,subtitle:b.subtitle,price:b.price,image:normalizeAssetPath(b.image_path),available:b.available,sort_order:b.sort_order,status:b.status,description:b.description,author:b.author,currency:b.currency,slug:b.slug}]));saveStoreConfig(config);saveBooks(books);return {config,books,backend:true}}catch(e){return {config:getStoreConfig(),books:{},backend:false,error:e}}}
async function invokePublicFunction(name,body){const sb=getSupabase();if(!sb)throw new Error('BACKEND_NOT_CONFIGURED');const {data,error}=await sb.functions.invoke(name,{body});if(error)throw error;return data}
async function getAdminSession(){const sb=getSupabase();if(!sb)return null;const {data}=await sb.auth.getSession();return data.session||null}
