(async function(){
const $=s=>document.querySelector(s);const form=$("#trackForm"),msg=$("#trackMessage"),result=$("#trackResult");
if(window.lucide)lucide.createIcons();
const params=new URLSearchParams(location.search);if(params.get("order"))$("#orderNumber").value=params.get("order");
function showMessage(type,text){msg.hidden=false;msg.className=`track-message ${type}`;msg.innerHTML=`<i data-lucide="${type==="error"?"circle-alert":"info"}"></i><span>${text}</span>`;if(window.lucide)lucide.createIcons()}
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function label(status){return ({PENDING_VERIFICATION:"Payment verification in progress",CONFIRMED:"Payment confirmed — Library access is being prepared",DELIVERED:"Payment confirmed — Library access is ready",REJECTED:"Payment proof rejected"})[status]||status.replaceAll("_"," ")}
function render(data){
const o=data.order;const steps=[["PENDING_VERIFICATION","Payment submitted"],["CONFIRMED","Payment verified"],["DELIVERED","Library access ready"]];
const rank={PENDING_VERIFICATION:1,CONFIRMED:2,DELIVERED:3,REJECTED:0}[o.status]||1;
result.hidden=false;result.innerHTML=`<div class="track-result-card"><div class="track-result-top"><div><small>ORDER</small><h3>${esc(o.order_number)}</h3></div><span class="status-pill status-${esc(o.status.toLowerCase())}">${esc(label(o.status))}</span></div><div class="track-result-meta"><div><span>Customer</span><strong>${esc(o.customer_name)}</strong></div><div><span>Amount</span><strong>${Number(o.amount).toLocaleString("en-US")} ${esc(o.currency)}</strong></div><div><span>Submitted</span><strong>${new Date(o.created_at).toLocaleString()}</strong></div></div><div class="track-timeline">${steps.map((s,i)=>{const active=o.status==="REJECTED"?false:i<rank;return `<div class="${active?"done":""}"><span class="timeline-dot">${active?"✓":String(i+1).padStart(2,"0")}</span><div><strong>${s[1]}</strong><small>${i===0?"Order received":i===1?"Admin verification completed":"Open My Library to start reading"}</small></div></div>`}).join("")}</div>${o.status==="REJECTED"?`<div class="track-reject"><strong>Payment not approved</strong><p>${esc(o.rejection_reason||"Please contact support for assistance.")}</p></div>`:`<div class="track-result-actions">${o.status==="DELIVERED"?`<a class="primary-btn" href="library.html">Open My Library <i data-lucide="library"></i></a>`:""}<a class="track-outline" href="mailto:dennisnazar123@gmail.com">Contact Support <i data-lucide="mail"></i></a></div>`}</div>`;
if(window.lucide)lucide.createIcons()
}
form.addEventListener("submit",async e=>{e.preventDefault();result.hidden=true;const order=$("#orderNumber").value.trim().toUpperCase(),email=$("#trackEmail").value.trim().toLowerCase();if(!order||!email)return;const sb=getSupabase();if(!sb){showMessage("error","Backend haijaunganishwa.");return}const btn=form.querySelector("button");btn.disabled=true;showMessage("info","Inatafuta order yako…");try{const {data,error}=await sb.functions.invoke("track-order",{body:{orderNumber:order,email}});if(error)throw error;if(data?.error)throw new Error(data.error);msg.hidden=true;render(data)}catch(e){showMessage("error","Order haijapatikana. Hakikisha Order Number na email umeandika kama ulivyotumia checkout.")}finally{btn.disabled=false}});
})();